screwdriver-cd/executor-k8s-vm

README.md, config/pod.yaml.tim, index.js, test/index.test.js
We want to allow builds to run inside a VM in Kubernetes. 
This pod yaml will pass arguments into `/sd/hyper-runner.sh`. This script is available in the  `{{base_image}}`, and is expected to start the VMs
`baseImage` is configurable by cluster manager via an environment variable: https://github.com/screwdriver-cd/screwdriver/pull/625/files
To allow build to run inside a VM in Kubernetes
Related to https://github.com/screwdriver-cd/screwdriver/issues/597
=> fix: add pod yaml

config/pod.yaml.tim
The comment actually comment the rest of the commands, so it doesn't do the cleanup
=> fix: remove comments

config/pod.yaml.tim
We would like to add a docker install script to the sdlauncher mount from the hyper runner pod to the build hyper container
=> fix: Add volume mount for sdlauncher

config/pod.yaml.tim
We have observed that a lot of pods got assigned to the same node around the same time. To better allocate resources, this PR will add `podAntiAffinity` to spread pods across nodes.
This blob means whenever it is possible, do not schedule the current build pod to a node that has a build pod running already.
All build pod has label `app: screwdriver-vm` and `kubernetes.io/hostname` is the hostname for node.
Reference: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname
@chestery Can you help review it?
=> feat: spread pods across nodes

screwdriver.yaml
switch to use semantic-release template
Builds are failing due to latest semantic-release requires node:8
https://cd.screwdriver.cd/pipelines/235/builds/12623
=> fix: switch to use semantic-release template

config/pod.yaml.tim, index.js, package.json, test/index.test.js
Currently, pod creation returns `201`, but afterward, it might fail at initcontainer, or after that. However, the error doesn't get caught because because `_start` already returns. So the status of the build stays as `QUEUED` forever even though the pod failed. 
This PR:
- checks the pod status after it's created. If the status is `failed` or `unknown`, it will throw error. The queue worker will catch this, retry, and report back to API that this build failed (https://github.com/screwdriver-cd/queue-worker/blob/master/index.js#L90-L91). 
- adds random string to pod name so that the queue can recreate the pod (currently unable to recreate pod if name is the same)
Resources:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase …
=> fix: checks pod status after creation

config/pod.yaml.tim, index.js
Worker is broken right now. 2 issues:
- affinity needs `weight`, and a couple other keywords
- podname cannot be uppercase
=> fix: affinity and pod name

index.js, package.json, test/index.test.js
Previously, body might not have `status.phase` so it actually just runs once and fails.
=> fix: retry when status is undefined

config/pod.yaml.tim, index.js, package.json, test/index.test.js
It would be nice if people could choose their CPU and RAM settings for jobs.
This PR sets resources:
- default - 2 vcpu, 2GB memory
- `HIGH` - 6 vcpu, 12GB memory
The resources can be configured by setting job-level annotation `beta.screwdriver.cd/resource: 'HIGH'`.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/631
- CPU: https://github.com/screwdriver-cd/screwdriver/issues/758
- RAM: https://github.com/screwdriver-cd/screwdriver/issues/759
=> fix(631): Add HIGH resource values for cpu and ram

config/pod.yaml.tim
Getting failures in the queue worker log:
```
error: err in start job:  Error: Failed to create pod: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: [pos 997]: json: expect char '\"' but got char '6'","reason":"BadRequest","code":400}
```
=> fix: Expecting quotes in arguments

index.js, package.json, test/index.test.js
Allow setting them separately
Related: 
https://github.com/screwdriver-cd/screwdriver/issues/758
https://github.com/screwdriver-cd/screwdriver/issues/759
=> fix: allow setting CPU and RAM separately

config/pod.yaml.tim
Screwdriver.cd is now using Init Containers with alpha annotations, but alpha annotations are not supported in Kubernetes 1.8 or greater.
Use new syntax of Init Containers.
Please refer to https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
- This new syntax doesn't work in Kubernetes 1.5
- same as https://github.com/screwdriver-cd/executor-k8s/pull/66
=> fix: update syntax of Init Containers

index.js, test/index.test.js
Currently, it defaults to require 2 cpu to start the pod. Our nodes have only 2 cpu so a lot of builds get stuck. This PR makes it configurable by the cluster, so we can modify this value to something smaller.
=> fix: make high/low cpu/memory configurable by the cluster

index.js, package.json, test/index.test.js
Allow `executor-k8s-vm` to use toleration config passed in by API so that build pods can work with taints set by cluster administrator.
Parse `tolerations` config and use that in pod spec.
Blocked on this PR https://github.com/screwdriver-cd/data-schema/pull/197
=> feat(827) use tolerations config

config/pod.yaml.tim, index.js
To provide users with the ability to gather metrics about their Kubernetes clusters, it would be nice to expose two environment variables, $METRIC_HOST and $NODE_ID to the Kubernetes pod. $METRIC_HOST would be injected from Screwdriver's ecosystem in `default.yaml`.
Modify the `pod.yaml.tim` to inject environment variables into a Kubernetes pod, so users can collect and send metric data.
* How to get a pod's node ID: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
=> Expose $METRIC_HOST and $NODE_ID to K8 pod

README.md, index.js
To provide users with the ability to gather metrics about their Kubernetes clusters, it would be nice to expose two environment variables, $METRIC_HOST and $NODE_ID to the Kubernetes pod. $METRIC_HOST would be injected from Screwdriver's ecosystem in `default.yaml`.
Modify the `pod.yaml.tim` to inject environment variables into a Kubernetes pod, so users can collect and send metric data.
* How to get a pod's node ID: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
* Screwdriver config PR: https://github.com/screwdriver-cd/screwdriver/pull/872
* Old PR that didn't trigger semantic-release: https://github.com/screwdriver-cd/executor-k8s-vm/pull/22
=> feat: Expose $METRIC_HOST and $NODE_ID to K8 pod

README.md, config/pod.yaml.tim, index.js
It was brought to my attention that "metric host" is vague, and implies that entering a URL to your metrics service would magically set everything up.
To reflect that this feature has been designed to only support [Prometheus pushgateways](https://github.com/prometheus/pushgateway), I've changed the nomenclature and comments to reflect that.
=> fix: Clarify "metric host" should be a Prometheus pushgateway URL

config/pod.yaml.tim, index.js, test/index.test.js
Build timeouts have a default value of 5400 seconds. We want to allow users to override the value. Eventually we will put in efforts to enforce boundaries on these values.
Use an annotation for users to configure their own timeouts. Default is 5400 seconds.
* Feature issue
* https://github.com/screwdriver-cd/screwdriver/issues/545
* Hyperctl parameter for build timeout
* https://github.com/screwdriver-cd/hyperctl-image/pull/19
=> feat: annotation for customizing build timeouts

index.js, test/index.test.js
The units of time for `build-timeout` is in minutes.
Correct all assumptions of _build-timeout_ from seconds to minutes.
* Feature issue
* https://github.com/screwdriver-cd/screwdriver/issues/545
=> fix: build timeout defined in minutes

index.js, package.json, screwdriver.yaml, test/index.test.js
Add an ability to configure preferred node affinity like https://github.com/screwdriver-cd/screwdriver/issues/827.
This PR adds `setPreferredNodeSelector` and updates `setNodeSelector` to use `requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution` at the same time.
This PR also adds some test cases and refactors the test.
- Related: https://github.com/screwdriver-cd/screwdriver/issues/972
- Similar PR: https://github.com/screwdriver-cd/executor-k8s/pull/77
- [Node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)
- [about weight](https://github.com/kubernetes/contrib/blob/fe159a635a0c4a5f4a3960cbef7f885091590dea/rescheduler/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities …
=> feat(972): use preferred node affinity config on k8s-vm

index.js, test/index.test.js
This PR adds missing if statement and fixes test data to be more detail.
Related: screwdriver-cd/screwdriver#972
=> fix(972): fix when a selector is empty object

index.js, test/index.test.js
Allow cluster admin to configure default build timeout for the cluster
Related: https://github.com/screwdriver-cd/screwdriver/issues/545
=> fix(545): cluster configurable build timeout

index.js, package.json, test/index.test.js
Resolving to `null` since it's not supported. 
We need this because models always call `_startPeriodic` for `update`
Blocked by: https://github.com/screwdriver-cd/executor-base/pull/39
Related: https://github.com/screwdriver-cd/screwdriver/issues/688
=> [2] fix: add start/stop periodic

.gitignore, config/pod.yaml.tim, package.json
This PR cp `hab` cache to the exsiting`sdlauncher` volume. Later I will open another PR in` hyperctl-image` to copy ` /opt/launcher/hab` to `/hab`. The reason why we don't mount it to `\hab` directly is due to security concern. `/hab` need to be writable, but all volume mounts for vm should be read-only since it's shared between VM and the host directly.
https://github.com/screwdriver-cd/hyperctl-image/blob/master/scripts/hyper-pod-template.json#L17
Related to https://github.com/screwdriver-cd/screwdriver/issues/877
=> feat: cp hab cache to sdlauncher volume

index.js, test/index.test.js
For issue https://github.com/screwdriver-cd/screwdriver/issues/1167 , we should exchange temporary JWT token in launcher, not in executor-*.
I removed calling exchangeTokenForBuild method form executor-k8s-vm.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1167
related PR:
launcher: https://github.com/screwdriver-cd/launcher/pull/201
executor-k8s: https://github.com/screwdriver-cd/executor-k8s/pull/88
executor-docker: https://github.com/screwdriver-cd/executor-docker/pull/27
executor-jenkins: https://github.com/screwdriver-cd/executor-jenkins/pull/23
=> feat(1167): [2][small] remove calling exchangeTokenForBuild method

index.js, package.json, test/index.test.js
Interface for circuit breaker got changed a long time ago but we never published it.
https://github.com/screwdriver-cd/circuit-fuses/blob/master/index.js#L229
pull in: https://github.com/screwdriver-cd/circuit-fuses/pull/23
https://github.com/screwdriver-cd/circuit-fuses/pull/24
=> fix: pull in new circuit breaker

config/pod.yaml.tim
add resources requests in k8s pod.
when k8s allocate resources it will simply sum up the requested resources for all the k8s pods. By reserving this resources, we can make sure hyper vm gets enough resources. This vm-launcher pod won't actually consume that much.
=> fix: add resources requests in k8s pod

index.js, package.json, test/index.test.js
When there is no K8S resources available, the pod will be pending. To bubble up this info to user, we will set build status msg if pod status is still pending after maxRetry.
When the build status got changed to `Running`, api will clear out the status msg set before that.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/update.js#L115
=> fix(757): set build status msg if pod is still pending after maxRetry

index.js, test/index.test.js
Currently all Screwdriver V4 builds default to a predetermined amount of storage space. We want to offer users the option to configure higher disk space for their builds.
Pass the annotation `beta.screwdriver.cd/disk` as a node selector/toleration. Nodes designated to support higher disk space per build will be labeled/tainted with `disk=high`.
https://github.com/screwdriver-cd/screwdriver/issues/757
=> feat(757): Pass disk annotation as toleration and node selector

index.js, test/index.test.js
We should use a less generic label than `disk=high`.
Change the toleration/pod affinity key from `disk` to `screwdriver.cd/disk`.
https://github.com/screwdriver-cd/screwdriver/issues/757
=> feat(757): Change toleration key from disk to screwdriver.cd/disk

index.js, test/index.test.js
Our current implementation of `setNodeSelector` appends multiple `nodeSelectorTerms` to the spec. This leads to an `OR` scheduling behavior where the pod can be scheduled on any node that is labled with any of the `nodeSelectors`. 
I believe we desire an `AND` scheduling behavior where the pod can be scheduled on any node that is labled with ALL of the `nodeSelectors`. This PR changes the implementation of `setNodeSelector` to honor this `AND` behavior of scheduling.
Update `setNodeSelector` to append multiple keys to a single `nodeSelectorTerm`
https://github.com/screwdriver-cd/screwdriver/issues/757
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
https://github.com/kubernetes/kubernetes/issues/44349
=> fix(757): Change setNodeSelector to use a single nodeSelectorTerm

index.js, test/index.test.js
Same as following PR.
https://github.com/screwdriver-cd/executor-k8s/pull/97
- Issues:
https://github.com/screwdriver-cd/screwdriver/issues/1261
=> fix(1261): pod delete immediately when build has stopped.

config/pod.yaml.tim
This `preStop` hook is no longer working since https://github.com/screwdriver-cd/executor-k8s-vm/pull/46 . So it might be removable.
This cleanup commands move to `hyper-runner.sh` ( https://github.com/screwdriver-cd/hyperctl-image/pull/26 )
Related: https://github.com/screwdriver-cd/screwdriver/issues/1378
=> fix(1378): [small] remove preStop hook

index.js, test/index.test.js
We added `gracePeriodSeconds: 0` option to delete pod immediately.
Now, we don't have to use this option because SIGTERM processing is done correctly https://github.com/screwdriver-cd/launcher/pull/228#pullrequestreview-180903853. 
Therefore, I remove `gracePeriodSeconds: 0`option and use default settings.
https://github.com/screwdriver-cd/screwdriver/issues/1261
https://github.com/screwdriver-cd/screwdriver/issues/1403
=> fix(1403): Remove graceperiod settings

index.js, package-lock.json, package.json, test/index.test.js
- add disk speed annotation / node selector
- if annotation not specified, can go to any node. If annotation specified, will go to the desired node with proper resources 
Blocked by: https://github.com/screwdriver-cd/executor-base/pull/51
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1463
=> fix: add disk speed annotation [2]

config/pod.yaml.tim, index.js, test/index.test.js
Currently, for each build, it's doing cp for all the launcher dependencies to the host. But for builds using the same launcher version, all the dependencies will be the same.
This PR will make the first pod on a node to do the `cp`, the later pods coming to the pod will just enjoy the benefit of the cache.
For deployment, this need to go out with the latest executor-k8s-vm
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1489
=> feat: cache launcher dependencies. BREAKING CHANGE: pod config changes

index.js, package.json, test/index.test.js
[An error message](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L407-L409
) was not shown on UI and a build status was not changed even if users use invalid image.
This might be caused by pod's waiting reason is `PodInitializing` after [these retrying](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L391-L400).
To prevent this problem, `MAXATTEMPTS` and `RETRYDELAY` should be configurable.
https://github.com/screwdriver-cd/screwdriver/issues/1678
=> fix(1678): [2] add configurable retryDelay and maxAttempts

README.md, index.js, test/index.test.js
The cluster admin might want to add new disk space or speed settings but don't want to make code changes each time. 
This PR will rename the disk space setting to something more generic (from `high` to `space`). Also will no longer check the user config value for the disk label(s).
=> fix: Allow any setting for disk space

index.js, test/index.test.js
By default, should not set disk space and speed tolerations and annotations in k8s when it is not configured in the annotation.
This PR does not set disk info by default.
Related to https://github.com/screwdriver-cd/executor-k8s-vm/pull/60
=> fix: Do not set disk toleration when annotation is not set

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim, index.js, test/index.test.js
In order to support build cache to disk strategy, kubernetes pods should be mounted with cache directory volumes, so builds can directly write to their respective cache directories
When cache strategy is disk, k8s build pods are created with their respective cache directory volumes that are mounted and available to the build.
=> feat(1830): k8s pod config changes to support cache to disk strategy

index.js
pipelineid is not available under config.meta instead under config.pipeline.id
Get pipelineid from config.pipeline.id
=> fix(1830): get pipeline id

index.js, test/index.test.js
Default values missing for cache strategy n path and move cache env variables under ecosystem
Add default values for cache env variables
=> fix(1830): default values for cache strategy n path

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim, index.js, test/index.test.js
add md5 check, compress, and cache max size 
=> fix(1830): add md5check, compress, maxsize capabilities to pod template

config/pod.cache2disk.yaml.tim
When a build is running as a non-root user, build cache fails with error "permission denied in set cache" when using disk-based strategy, due to permission issue on created folders.
This PR will give permissions to build related folders
[1887](https://github.com/screwdriver-cd/screwdriver/issues/1887)
=> fix(1887): fix build cache folder permissions

config/pod.cache2disk.yaml.tim, index.js, package.json
PR builds get cache fails for job level cache scope.
This PR will fix get cache issue at job level scope, regex pattern to identify PR and mount read-only job cache volume.
https://github.com/screwdriver-cd/screwdriver/issues/1905
=> fix(1905): PR builds to get cache at job level cache scope

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim, index.js
Error: tim: 'cache_max_go_threads' not found in {{cache_max_go_threads}}
in pod creation definition, change var name max_go_threads to cache_max_go_threads
[executor-k8s-vm-PR#75](https://github.com/screwdriver-cd/executor-k8s-vm/pull/75)
=> fix: typo cache-max_go_threads

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim, index.js, test/index.test.js
Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case, so we need to increase the grace period before pod termination to run the artifact saving steps
This PR adds provision to increase pod timeout by using annotations
https://github.com/screwdriver-cd/screwdriver/issues/1125
=> feat: add terminationGracePeriodSeconds annotation

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim
Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case, so we need to increase the grace period before pod termination to run the artifact saving steps
This PR adds pod timeout configuration to env var
https://github.com/screwdriver-cd/screwdriver/issues/1125
=> feat: add terminationgraceperiod env var

config/pod.cache2disk.yaml.tim, config/pod.yaml.tim
New env var in pod caused error as it was not the correct type
This PR changes the env var to string to fix the error
=> feat: fix pod template
